-- Enable the necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. PROFILES
-- ==========================================
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  first_name text,
  last_name text,
  email text,
  role text DEFAULT 'customer', -- 'customer' or 'admin'
  has_scanned boolean DEFAULT false,
  measurements jsonb DEFAULT '{}'::jsonb,
  brand_sizes jsonb DEFAULT '{}'::jsonb,
  style_prefs text[] DEFAULT '{}',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 2. PRODUCTS
-- ==========================================
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  brand text NOT NULL,
  category text NOT NULL,
  gender text DEFAULT 'Unisex',
  price numeric NOT NULL,
  original_price numeric,
  images text[] NOT NULL,
  colors text[] DEFAULT '{}',
  sizes text[] DEFAULT '{}',
  rating numeric DEFAULT 0,
  reviews integer DEFAULT 0,
  fabric text,
  care text,
  description text,
  tags text[] DEFAULT '{}',
  in_stock boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. ORDERS
-- ==========================================
CREATE TABLE public.orders (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text DEFAULT 'Pending', -- 'Pending', 'Paid', 'Dispatched', 'Delivered'
  total_amount numeric NOT NULL,
  shipping_address jsonb NOT NULL,
  items jsonb NOT NULL, -- array of { product_id, size, quantity, price }
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 4. REVIEWS
-- ==========================================
CREATE TABLE public.reviews (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  images text[] DEFAULT '{}',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 5. DELIVERIES (Tracking)
-- ==========================================
CREATE TABLE public.deliveries (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
  agent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- the delivery driver
  status text DEFAULT 'Preparing', -- 'Preparing', 'In Transit', 'Delivered'
  current_lat numeric,
  current_lng numeric,
  last_updated timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 6. SHONA DICTIONARY (For AI Search)
-- ==========================================
CREATE TABLE public.shona_dictionary (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shona_term text UNIQUE NOT NULL,
  english_translation text NOT NULL
);

-- Insert initial terms for the dictionary
INSERT INTO public.shona_dictionary (shona_term, english_translation) VALUES
('shangu', 'shoes'),
('bhurugwa', 'pants'),
('hembe', 'shirt'),
('rokwe', 'dress'),
('bhachi', 'jacket'),
('heti', 'hat');

-- ==========================================
-- 7. HOMEPAGE PROMOTIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS public.promotions (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  image_url text,
  link_url text,
  cta_text text,
  is_active boolean DEFAULT true,
  start_date timestamptz,
  end_date timestamptz,
  priority integer DEFAULT 0,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.home_deals (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  image_url text,
  link_url text,
  badge_text text,
  is_active boolean DEFAULT true,
  start_date timestamptz,
  end_date timestamptz,
  priority integer DEFAULT 0,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shona_dictionary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_deals ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can read/insert/update their own profile
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Products: Anyone can read, only admins can modify
CREATE POLICY "Anyone can view products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admins can modify products" ON public.products FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Orders: Users can read their own orders, admins can read all, guests can read/insert their own guest orders
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT WITH CHECK (user_id IS NULL OR auth.uid() = user_id);
CREATE POLICY "Admins can view all orders" ON public.orders FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update orders" ON public.orders FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Reviews: Anyone can read, authenticated users can insert
CREATE POLICY "Anyone can view reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Deliveries: Users can track their own deliveries, Agents can update
CREATE POLICY "Users can view own deliveries" ON public.deliveries FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.orders WHERE public.orders.id = public.deliveries.order_id AND public.orders.user_id = auth.uid())
);
CREATE POLICY "Delivery agents can update their deliveries" ON public.deliveries FOR UPDATE USING (auth.uid() = agent_id);
CREATE POLICY "Admins can view all deliveries" ON public.deliveries FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Dictionary: Anyone can read
CREATE POLICY "Anyone can view dictionary" ON public.shona_dictionary FOR SELECT USING (true);

-- Homepage promotions: Select active items publicly, admin can manage all
CREATE POLICY "Anyone can view active promotions" ON public.promotions FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage promotions" ON public.promotions FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Homepage deals: Select active items publicly, admin can manage all
CREATE POLICY "Anyone can view active deals" ON public.home_deals FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage deals" ON public.home_deals FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ==========================================
-- 7. MESSAGES (Buyer-Seller Chat)
-- ==========================================
CREATE TABLE public.messages (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  content text NOT NULL,
  image_url text,
  status text DEFAULT 'sent', -- 'sent', 'delivered', 'read'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages" ON public.messages FOR SELECT USING (
  auth.uid() = sender_id OR auth.uid() = receiver_id OR EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "Users can send messages" ON public.messages FOR INSERT WITH CHECK (
  auth.uid() = sender_id
);

-- ==========================================
-- ENABLE REALTIME REPLICATION FOR ACTIVE TABLES
-- ==========================================
alter publication supabase_realtime add table public.deliveries;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.orders;

-- ==========================================
-- 7. REALTIME BROADCAST QUEUE + TRIGGER
-- ==========================================
-- Supabase Realtime broadcasts require a server-side mechanism.
-- This table + trigger is a common pattern: enqueue a payload row, trigger publishes.

CREATE TABLE IF NOT EXISTS public.realtime_broadcast_queue (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  channel text NOT NULL,
  event text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.realtime_broadcast_queue ENABLE ROW LEVEL SECURITY;

-- Only admins can insert into the queue
CREATE POLICY "Admins can enqueue broadcasts" ON public.realtime_broadcast_queue
FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin')
);

-- Disable all other access (keep it tight)
CREATE POLICY "Disable select" ON public.realtime_broadcast_queue FOR SELECT USING (false);
CREATE POLICY "Disable update" ON public.realtime_broadcast_queue FOR UPDATE USING (false);
CREATE POLICY "Disable delete" ON public.realtime_broadcast_queue FOR DELETE USING (false);

ALTER PUBLICATION supabase_realtime ADD TABLE public.realtime_broadcast_queue;
